### ISSUE TITLE
Surface and groundwater regulatory and management agencies in the Western US

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/WestDAAT#1]
We need an interactive Tableau dashboard that visualizes all the Surface and groundwater regulatory and management agencies in the Western US and shows the differences in statues in SW and GW. 

Here is a good starting point. 
https://scholar.law.colorado.edu/cgi/viewcontent.cgi?article=1004&context=groundwater-in-west

The dashboard should have a map of the western 18 states. When the user clicks at a state, it should list the agencies that regulate and manage water and their URLs. It should also list how GW and SW are governed (e.g., connected or separate).

The purpose of the dashboard is to show the diversity in governance methods to help us identify the role of water data collection in sharing across the west.

**Comment by rwjam** [comment]
Started a shared spreadsheet to use as an input file for this project.  Can reorganize to better fit data if need be.

Link: https://docs.google.com/spreadsheets/d/1pxnmqVcaDZ8V7oHdzlu2XW3wuIecEjOnOyF-jBD5VQ8/edit#gid=0

**Comment by amabdallah** [comment]
I came across this interesting "Local government fragmentation" map and we eventually will do something like it but instead of municipalities, it will be water-related regulatory agencies 

![image](https://user-images.githubusercontent.com/3268971/144478166-9846334b-82c3-4b92-b508-d99719d3831d.png)

**Comment by amabdallah** [comment]
EPIC has done this work. Our goal is to add a time series of historic water use to each "city/utility"
https://lincolninstitute.maps.arcgis.com/apps/instant/interactivelegend/index.html?appid=f5bf4babf66c4d72af88e13728da7ade
