### ISSUE TITLE
WestDAAT Water Right Record Centric Landing Page Update & Feedback (05/31/2022) - WR Card, WaDe & Native term, update site table

### ISSUE THREAD

**Issue by rwjam** [WSWCWaterDataExchange/WestDAAT#113]
For the WestDAAT Water Right Record Centric Landing Page, here are some elements we would like to see included / updated.

1. Single water right info Card that shows info from the  Core.AllocationAmounts_fact table (see sample image)
2. Displaying both 1) WaDE Terminology and 2) state provided Native Terminology on the same line (see below list for examples).
3. Update the sites table to also include "Coordinate Method" & "Coordinate Accuracy" fields from the Core.Sites_dim table (see sample image)

The Water Right Record Centric Landing Page helps us illustrate a 1-m relationship between a water right record and its related site(s).  We like the design of this demo landing page, and would like to see something like this developed for WestDAAT.  We would like to see all informative water right record information from the Core.AllocationAmounts_fact table displayed on a card with an **up-&-down scroll ability**.  

We need a way to show both the state provided native terms (i.e., the stuff given to us) & the WaDE terminology (i.e., the stuff we use on the filters) on the returned data.  Below (see table / list) is an idea we had.  We would like to try and show both the WaDE Terminology & the state provided Native Terminology on the same line, separated out by a '|' symbol.  For example, say the WaDE Terminology = Agriculture Irrigation, and the  state provided Native Terminology = Cranberry, the resulting item in the card would look like...

 WaDE Beneficial Use | Native Beneficial Use |
---------- | ----------
Agriculture Irrigation | Cranberry

Lastly, we would like to update the sites table at the bottom on the to also include the "Coordinate Method" & "Coordinate Accuracy" fields from the Core.Sites_dim table.

Here is the list of items we would like to see on that water right record information card, in order (with more important features appearing at the top).
- WaDEUUID for water right (coming soon) (maybe for now cheat and use the AllocationAmountID as a temp place holder) 
- Native ID
- Owner Classification
- Owner
- Priority Date
- Expiration Date
- WaDE Legal Status | Native Legal Status
- Allocation Flow (CFS)
- Allocation Volume (AF)
- WaDE Beneficial Use | Native Beneficial Use
- Application Date
- Data Publication Date
- Data Publication DOI
- Exempt
- WaDE Power Type | Native Power Type
- Generated Power Capacity (MW)
- SDWIS Identifier
- Timeframe Start
- Timeframe End
- Legacy Allocation ID(s)
- Community Water Supply System Name
- WaDE Customer Type | Native Customer Type
- Population Served
- WaDE Crop Type | Native Crop Type
- WaDE Irrigation Method | Native Irrigation Method
- Irrigated Acreage (AF)
- Crop Duty Amount (AF)
- WaDE Primary Use Category
- Water Allocation Native URL

![image](https://user-images.githubusercontent.com/17555073/171289710-fa8ecd85-a34d-49ad-b73f-a605af7945f0.png)

![image](https://user-images.githubusercontent.com/17555073/171293212-6f8a2421-347b-43a4-af53-dea63b8f873c.png)

**Comment by EverettRhodes** [comment]
Update the sites table to also include "Coordinate Method" & "Coordinate Accuracy" fields from the Core.Sites_dim table (see sample image)
 - Only include Coordinate Method for now. Coordinate Accuracy does not have data in the DB right now

**Comment by EverettRhodes** [comment]
Need to look at native fields and estimate what it will take to return those from the API

**Comment by amabdallah** [comment]
Summarized the additions here

![image](https://user-images.githubusercontent.com/3268971/211574128-93df0c32-d220-4bf5-86ac-b4407b8a3c6f.png)
