### ISSUE TITLE
WestDAAT Site-Centric Landing Page Update & Feedback (05/31/2022) - Create Site Card, update site card, Water Right Summary Table

### ISSUE THREAD

**Issue by rwjam** [WSWCWaterDataExchange/WestDAAT#114]
For the WestDAAT Site-Centric Landing Page, here are some elements we would like to see included / updated.

1. Let's move the info in the sites table up to a card (see sample image).
2. Update the sites card to also include "Coordinate Method" & "Coordinate Accuracy" fields from the Core.Sites_dim table (see sample image)
3. For the Water Rights Information Table, let's only provide an abridged summary of the water right record(s), and save the full water right info for the Water Right Record Centric Landing Page.

The Site-Centric Landing Page helps us illustrate a 1-m relationship between a site and the many water right record(s) it might have.  We would like to update the site centric landing page to help empathies this 1-m relationship.  We like the idea of moving the info in that site table, for the given single site, up to a card with an **up-&-down scroll ability**.

In addition, lets put a little more site info on that card.  We would like also like to update the sites card to include the "Coordinate Method" & "Coordinate Accuracy" fields from the Core.Sites_dim table.

For the water rights information table on this landing page, we are thinking of only showing a abridged version of the full water rights information (so not everything from the Core.AllocationAmounts_fact table, just a summary).  We want to keep it simiple for now here and only show the WaDE terminology.  Here is the list of items we would like to see on that water rights information table on this site centric landing page, in order (with more important features appearing at the top).
- WaDEUUID for water right (coming soon) (maybe for now cheat and use the AllocationAmountID as a temp place holder) 
- Priority Date
- WaDE Owner Classification
- WaDE Legal Status
- Allocation Flow (CFS)
- Allocation Volume (AF)
- WaDE Beneficial Use

![image](https://user-images.githubusercontent.com/17555073/171294713-5abcf685-2ebd-4770-96ab-733c6327e6ad.png)
![image](https://user-images.githubusercontent.com/17555073/171294992-4610d5a7-1af4-4720-8a9f-3416919d9da6.png)

**Comment by EverettRhodes** [comment]
Update the sites card to also include "Coordinate Method" & "Coordinate Accuracy" fields from the Core.Sites_dim table (see sample image)
 - these will be half populated but there should be something in the fields. As of now they might be blank or unspecified
 - Only include Coordinate Method for now. Coordinate Accuracy can wait until there is data in the DB for that field

For the water rights table these are all the WaDE terminolgy

**Comment by amabdallah** [comment]
New task: Update the site's landing page to include the "Coordinate Method" & "Coordinate Accuracy" fields from the Core.Sites_dim table. Example site landing page https://westdaat.westernstateswater.org/details/site/UTwr_S115862
