### ISSUE TITLE
WaDE and OpenET integration on our dashboard 

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/WestDAAT#14]
Suggestions:
High level bold title: Interoperability with OpenET Data. Let's add a (?) info here where it shows a box of text on what OpenET is.
Second level title: Compare aggregate permitted water vs estimated consumptive water use 

Let's update the labels to these:

Label: Comparison year

Label: Boundary type 

Label: OpenET model 

Label: OpenET variable

![image](https://user-images.githubusercontent.com/3268971/139485781-d0218cb4-b259-4b69-9f19-aa7900b04b92.png)

**Comment by rwjam** [comment]
changes made and pushed to mockup.
