### ISSUE TITLE
Water rights filter location

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/WestDAAT#18]
1. Let's move the Allocation Owner filter to be next to the owner classification. It's more logical to have them next to each other. I think users care less about the type of filter (general search or drop down menu) but probably rather expect relevant filters to be next to each other. For example, I want to tell the story how WestDAAT supports searching by owner name or their classification. So it helps if both of these filters are next to each other.

2. Let's use the term "Water right" in WestDAAT not allocation. So let's make it "Water right owner name"   

![image](https://user-images.githubusercontent.com/3268971/139688491-4be2502c-cc4e-423a-aee2-44e09803ce64.png)

**Comment by rwjam** [comment]
- Renamed Search Allocation Owner search box -to- "Search Owner Name" to be more descriptive on the intent of the search box and to further remove the world Allocation from the app.
- Renamed "Owner Classification" drop down menu filter -to- "Owner Classification Type" to emphasize that his is a WadE vocabulary defined term.
- Moved the Search Owner Name search box down next to the Owner Classification Type drop down menu filter.
