### ISSUE TITLE
Issue with Prod pie chart colors 

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/WestDAAT#180]
See these two links and screenshots below. The issue appears when Idaho or Montana is selected (one at a time). Not sure about other states. We need to test further.

https://westdaat.westernstateswater.org/?state=N4Ig7gTiBcoM4BcCGCCmcYG0QEkAiIAugDQgAOA9gDYCeVAlgHapYkiNUAm9AYvVWgh4USGKCop6CAK6cW0RtKpVSVCowDmU2fMXLS3CKgDGCeuozQAzAZEAFCkwSWA7AF83pALZIyYkABeFBReADKoAG6oVDAArAB0AAwATABsAIzJLi4AHOnpqQCcACzFsaqSMnIwxcnxycmJhYmJOakuibHpscWq6lpV8gC0%2BYnxVi5FmcXNrbE5HkA
![image](https://user-images.githubusercontent.com/3268971/187985442-10787af3-6621-4ee4-85d3-299771ef1441.png)

https://westdaat.westernstateswater.org/?state=N4Ig7gTiBcoM4BcCGCCmcYG0QEkAiIAugDQgAOA9gDYCeVAlgHapYkiNUAm9AYvVWgh4USGKCop6CAK6cW0RtKpVSVCowDmU2fMXLS3CKgDGCeuozQAzAZEAFCkwSWA7AF83pALZIyYkABeFBReADKoAG6oVDAArAB0AAwATABsAIzJLi4AHOnpqQCcACzFsaqSMnIwxcnxycmJhYmJOakuibHpscWq6lpV8gC0%2BYnxVi5FmcXNrbE5HkA

![image](https://user-images.githubusercontent.com/3268971/187985424-6c9b9ec4-6a19-4417-a37e-b4283b635c19.png)

**Comment by amabdallah** [comment]
Stagging does not seem to load for me 

https://westdaatstaging.westernstateswater.org/?state=N4Ig7gTiBcoM4BcCGCCmcYG0QEkAiIAugDQgAOA9gDYCeVAlgHapYkiNUAm9AYvVWgh4USGKCop6CAK6cW0RtKpVSVCowDmU2fMXLS3CKgDGCeuozQAzAZEAFCkwSWA7AF83pALZIyYkABeFBReADKoAG6oVDAArAB0AIwuLrFWAJzpAGzpAExWqZmqkjJyMAAsufEADC6JidWxWVaxyQAciVmq6lql8gC09dXxbVa51dW5ueXl1Vm1WR5AA

**Comment by rwjam** [comment]
- Both those links share the same ID pie chart results on the production.  I believe you meant to share a MT example.
- https://westdaat.westernstateswater.org/?state=N4Ig7gTiBcoM4BcCGCCmcYG0QFkAqIAugDQgAOA9gDYCeVAlgHapYkiNUAm9AYvVWggARFEhigqKeggCunFtEYyqVUlQqMA5tLkKlK0twioAxgnoaM0AMyHRABQpMEVgOwBfd6QC2SMuJAALwoKbwAZVAA3VCoYAFYAOgAGACYANgBGFNdXAA4MjLSATgAWEri1KVl5GHKE6xSktJLG3KS43Jy0tQ1taoUAWgyk1wSiwqLcuLy0tOsi%2Bc8gA

**Comment by rwjam** [comment]
- A recent remap for ID data seems to have solved that issue, at least for ID (see shared uat link).  I will take another look at MT.  Most likely an issue with our CV google sheets and our CV tables in the prod database not updating properly.
- Some good analytics there.  Looks like some of those Unspecified uses have a VERY large use.  Not sure what would cause them to be that high.  Might be good examples to share with ID and ask directly what these & why are they so high.
-https://westdaatstaging.westernstateswater.org/?state=N4Ig7gTiBcoA4HsA2BPJBLAdgUxgbQF0AaETJAE3QDF0kAXbCAEQEM6WZQk306BXcrmiY%2BSJCSQJMAc14ChIsSUoRsAYzropAZxgBmZWxYAFBFjq7oAdgC%2BJbewaW8IAJJMQxEACNsOAGboaugsSACq2tjOBHYgALYscJwgAF4ICHEAMtgAbthIMABsAHQArKWFhQBMAAx6eqUAnHoAHIWlAIwSPPyCMAAsesWV9ValVv2F-VX9HS0SUrK9QgC0HR1DVXpVVaX1jVPltiSQ5MmI5gDK6ClCIP4gJAlwAOIQCHxwWNIwPnwgNhsQA
