### ISSUE TITLE
OK Water rights: Check owner name pattern 

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/WestDAAT#195]
See this owner name pattern (highlighted in red). Is that a source as-is issue? 

![image](https://user-images.githubusercontent.com/3268971/197033141-536cbac4-bbc3-4af5-a53f-d3437b13e6b7.png)

**Comment by rwjam** [comment]
For the most part, yes.  With the exception that we remove special characters where we can.  We use comma separated commands throughout out WaDE input scripts / WestDAAT filters, so if we don't remove them the system act's like there are multiple inputs when in reality it's there is only the one.

See OK wr input data for more examples: https://drive.google.com/drive/folders/18MPjzdWSJziv8XbSxe7A1fTjcmuPOizx?usp=sharing

![image](https://user-images.githubusercontent.com/17555073/197575308-541a615c-2ef6-43b4-b178-0c15fa7b2436.png)

**Comment by amabdallah** [comment]
Thank you. So all is good. It's the state's data that is not in the best shape :(
