### ISSUE TITLE
Review WA POU layer

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/WestDAAT#199]
We received this issue through WestDAAT feedback. 

1. **This single domestic use is mapped as a giant polygon. Is that correct?** https://westdaatstaging.westernstateswater.org/details/right/WAwr_WR61184?state=N4IgtgziBcIQhgFwKYBtUEsUFoBuBOEAGnHgAcZQAvAexrABllc0Z8A6ANgGYAGAVgAsvQQCZO%2BfLxEB2EqiRYArgBNkMQTPYyZnMQA5%2BARhkme-TvJoA7AObK1MbEdGj2RscKOTuM0f1FuAF8goA

2. **Why are municipal service area polygons in the (Seattle/Tacoma/Everett) area not showing up?** 
Comment by Adel: I'm not sure if the original dataset has them. Let's go over it. Here is a link for the area. We might need to double-check the beneifial use mapping in Washinton. Domestic should be for indicial owners, not cities. Cities should have a Public water supply. Not suggesting anything is wrong, but worth reviewing.
https://westdaatstaging.westernstateswater.org/?state=N4Ig7gTiBcoEYFMB2CBmBLAxughgGwFUBnBImAbXmTS10JIDkcBbBGEAEQHtWiAXLCAA0ITFyREArswAOA8QGEcfBAHMuEAJ4wAjAF8hVFBmz5iCJq3YBZSUloz8AAgCSECOlXL044aPFSsvJISirqWjAATAZGNKb0Fixs0CAACpJweFhOAMqSMjJ42iJiEtJyPiHKahra0PoAuiLM6EgAalx40sk6AAwiMlwAJqlckuypAPIEfoNFWSgUTSBIeEPoAGLoeCoQHMo4MKB43nySQ8lIknh4InjiquhnFzBXNyLrEAiYwWTQAMwfA6jVp8P4Adj0BhAzBwMiOIAAXlweAAZBAANwQeF0vQAdL0dABWAAshIAHOSdAA2SLUqngu6nc7JEngvFEzkkyIATiJkX%2BlPB5KJdweTxZMAAtDpIpE8X0eTydOCib1Of8%2BVCgA

**Feedback**

First Name:
        Andrea
Last Name:
        Lauden
Satisfation:
        Somewhat satisfied
Comments:
        I see some issues with Washington State polygons - ex. Allocation UUID WAwr_WR61184 is a single domestic use mapped as a giant polygon. And I'm not seeing the municipal service area polygons identified as the water right authorizations that I would expect to see in that (Seattle/Tacoma/Everett) area.
Email:
        [andrea.lauden@ecy.wa.gov](mailto:andrea.lauden@ecy.wa.gov)
Organization:
        WA Dept. of Ecology
Data Usage:
        - General Interest
        - Regulatory

**Comment by rwjam** [comment]
> Q: This single domestic use is mapped as a giant polygon. Is that correct?

That WA water right (i.e., WR Doc ID = 2274342) is being mapped to both a single POD ([link](https://westdaatstaging.westernstateswater.org/details/site/WAwr_S115289?state=N4IgtgziBcIQhgFwKYBtUEsUFoBuBOEAGnHgAcZQAvAexrABllc0YBWAOgBYAmAZgDsAgIwA2Pm0F8uYkqiRYArgBNkMLgI4AGNgLY8ufUaIHSBcmgDsA5ktUxswnlu79hXfFoE8BotvmEAX0CgA)) and that larger POU ([link](https://westdaatstaging.westernstateswater.org/details/site/WAwr_S175121?state=N4IgtgziBcIQhgFwKYBtUEsUFoBuBOEAGnHgAcZQAvAexrABllc0YAWAOgDY2B2LgKxd8I-LzZsAHACYSqJFgCuAE2TsuHafkEBGNgAZJvAMz5J%2BWSFQ0AdgHMlqmNh07eHAQck6BO48a59EQEAXxCgA)).  That connection is being made as both sites share the same WR_DOC_ID, used to identify water right ID, as identified from the provide source data found here ([link](https://fortress.wa.gov/ecy/gispublic/DataDownload/wr/GWIS_Data/)).

Interesting enough, WA’s own water right resources are not accrediting that larger POU to the same WR, only on the single POD ([see record link here](https://appswr.ecology.wa.gov/waterrighttrackingsystem/WaterRights/WaterRightRecord.aspx?from=Map&waRecId=2274342&nav=WaRecHyperLink0&btnCount=1&initialActiveTabIndex=0#no-back-button)).  Whether that is an issue with our mapping approach or a fault in the provided source data is not known.


---------------------------
> Q: Why are municipal service area polygons in the (Seattle/Tacoma/Everett) area not showing up?

The provide source data found here ([link](https://fortress.wa.gov/ecy/gispublic/DataDownload/wr/GWIS_Data/)) does not give site name for any POU areas.

**Comment by amabdallah** [comment]
@rwjam This is the original issue reporting the problem in WA data

**Comment by rwjam** [comment]
the westdaat stagging link to the WAwr_WR61184 (i.e., the single domestic ue mapped as a giant polygon) is no longer viable and we can no longer follow up on this.
This GitHub issue was created before we made changes to how we create UUIDs, so it's not really possible anymore to track what site they were refering too.



Everett [westdaat Link](https://westdaatstaging.westernstateswater.org/details/right/WAwr_WR2274061?state=N4IgtgziBcIQhgFwKYBtUEsUFoBuBOEAGnHgAcZQAvAexrABllc0YBGABgDo2A2AJgCsvQfgAc%2BcRwAsAdlklUSLAFcAJshhyu%2BQbJltZ0-n0H8FIVDQB2Ac1UaY2Nv35cZAZl4cxB878EAX0CgA)
Seattle Public Utilities  [westdaat Link](https://westdaatstaging.westernstateswater.org/details/right/WAwr_WR4321447?state=N4IgtgziBcIQhgFwKYBtUEsUFoBuBOEAGnHgAcZQAvAexrABllc0YBGNgOgDYAOfAOwBWIfiFtuAFja9uJVEiwBXACbIYkgZ1FDeHNgGZ8ABkMAmM-JoA7AObK1MbGwucDBycaEfeA7gN4zbgBfYKA)
Seattle City Water Department  [westdaat Link](https://westdaatstaging.westernstateswater.org/details/right/WAwr_WR4726968?state=N4IgtgziBcIQhgFwKYBtUEsUFoBuBOEAGnHgAcZQAvAexrABllc0Z8A6AVgHZ8BGAEwA2IQGYBo7kIAMvEqiRYArgBNkMACzd2QgdM6cAHAaFHOAw-JoA7AObK1MbIIHtpu0UPyjRh7tNFpfABfYKA)
Tacoma  [westdaat Link](https://westdaatstaging.westernstateswater.org/details/right/WAwr_WR2218982?state=N4IgtgziBcIQhgFwKYBtUEsUFoBuBOEAGnHgAcZQAvAexrABllc0YBGABgDoOBmAFgBsADjb82Adn4AmDv3klUSLAFcAJshj8JXNvgkS5AVmETe0qdMU0AdgHNVGmNjbTpXXmyMDRg6f14DaQBfYKA)

**Comment by amabdallah** [comment]
Thanks for the review and making the fixes. Looks great to me
