### ISSUE TITLE
Priority Date Filter Components.

### ISSUE THREAD

**Issue by rwjam** [WSWCWaterDataExchange/WestDAAT#2]
(Ryan McManaman) I've got some questions regarding the priority date filter component.  As discussed, the filter needs to be a slider that lets a user select a start/end date for the rendered allocations.  Looking at the schema, the allocations have one priority date, but a priority date can have multiple allocations.  An allocation can also have a null priority date value.  With that in mind:

Q: What happens when an allocation has no priority date and a user selects an end/start date? Do we render all null values or none of them?

Q: How is expiration date factored into the filter? For example, if a priority date occurs before the filter's start date but hasn't expired, does it get rendered (e.g. Priority Date is Oct 1, Start Date is Oct 31st in the filter, Expiration Date is Dec 1)?

Q: Is there a scenario where the priority date falls within the selected range but shouldn't be rendered?

**Comment by rwjam** [comment]
> Q: What happens when an allocation has no priority date and a user selects an end/start date? Do we render all null values or none of them?

- Ideally, we probably want to add a check box that says: Include Rights with No Priority Date. If checked, then you would include all the sites with a null priority date.  If this box is not checked, they should be hidden.  This check box should query the WaDE “ExemptOfVolumeFlowPriority” field we added.
- For range filtering, here is how I think of it working conceptually:  Filter the water allocation table based on a priority date min and max values of month and year (i.e mm/yyyy). So if the priority date of mm/yyyy falls within this range, then render it.  If not, it should not be visible.
- If implementing this feature turns out to be really time consuming (i.e., more than ~4 hrs), let's simplify this demo by rendering all null priority values at all the time for now, and we will address this later.

> Q: How is expiration date factored into the filter? For example, if a priority date occurs before the filter's start date but hasn't expired, does it get rendered (e.g. Priority Date is Oct 1, Start Date is Oct 31st in the filter, Expiration Date is Dec 1)?

- I would ignore the “expiration date” field for now.  A priority date, in theory, never expires. We will address this at a late date.

> Q: Is there a scenario where the priority date falls within the selected range but shouldn't be rendered?

- The only scenario I can think of is making sure the view also considered other filters.  For example, say the user only wants to view rights related to groundwater.  In this example case, all the rights that fall within the priority date search and are groundwater would be visible. I guess this is obvious but it doesn’t hurt to mention.

**Comment by amabdallah** [comment]
This seems to me as resolved and addressed in our current implementation.  
![image](https://user-images.githubusercontent.com/3268971/226504695-ab5afc4f-edda-47fc-9a41-2f6882b2f71d.png)
