### ISSUE TITLE
Aggregate Water Data landing page

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/WestDAAT#20]
In WaDE 1.0 catalog front end dashboard, we used to show a pie chart for the water budget across categories of use of a selected "area" if the state has many variables reported. I think we also showed a pie chart of water use across beneficial uses. This is a very useful insight.

1. Let's add a pie chart plot (for the many categories of use of the same year) on the landing page probably below the time series plot (USGS landing pages allow multiple plots on their landing page). We probably could make the plot "variable" to be "category of use", "water source type", and "VariableCV"
https://waterdata.usgs.gov/monitoring-location/10142000/#parameterCode=00065&period=P7D
![image](https://user-images.githubusercontent.com/3268971/139696785-5d19d842-cceb-4874-900b-17ad2efa8c31.png)

2. Let's add a polygon map similar to the water right POD landing page. This is a feature of the Geoconnex landing pages which we have a deliverable for https://geoconnex.internetofwater.dev/demo/

![image](https://user-images.githubusercontent.com/3268971/139697173-a8b249fc-a039-4775-bdb2-f8c281c5419a.png)

**Comment by rwjam** [comment]
- Added a pie chart analytics tab to the plot information.  Split up between Beneficial Use, Water Source Type, & Variable Type.
- Moved Polygon Map to below filers & text and above plot information.
- Lots of info on page now.  Added Scroll Function & Scroll Bar (not animated) to landing page to emphasize the amount of available information shown on a single aggregated data landing page.
