### ISSUE TITLE
Owner name bug? Bushman family as an example

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/WestDAAT#200]
There is an interesting discrepancy at least between the Prod database and what is viewed in WestDAAT. 

**Story**
Michelle mentioned to me in the office today that she coincidentally came across water rights in her family's name in Arizona local database search (while looking into terminology stuff). So she was curious if her family has water rights through WestDAAT. I looked and found a bunch of rights in her family name. 

**Expected**
The download function worked perfectly fine to show the list in this example in Idaho (see the WestDAAT link below and the CSV downloaded file)

**Unexpected (bug?)**
When I visit many of the landing pages of these 10 example sites, I see owner names that have nothing to do with Bushman at all. Also, those names dont show up at all in the downloaded CSV file. 

**Speculation**
Is the Mapbox in Prod out of data compared to the database? There could be an issue in DPL's code that generates the sites for Mapbox/landing pages. No idea.

https://westdaat.westernstateswater.org/?state=N4Ig7gTiBcoIYBsEHsDGcAuBLZA7A8mLgKZTQgBGArgM4AWAtnLiADQgAOyCAngliRgBtUFgAmxXNgBmWUjBDTiARgAsAVgAcysZtSoxATgrri61QHZ1AZmsAGO6k2qxcAEyaAbGxCuMcGFExBSU1LR09A2NTcytbBycXdy8fDB4OYgUAMWJMKghM9g4IZAyIbGIaQIBfdgBzYmQGYgwIHkCQVGRkCDEBTErhISEAWmVxgDoNOzc7C09PN09VQ2tPVlU3KbdDB08LTbnPLQBdVlHx5QnrQ3VDVU03DXtzNw2tzfVlrxvVO1UAWcLpMbtY3Oo3MpwcpNJpDJp3lN-g4wcp5oZlHZlECxpMNIY3ITtJtYQTETcCVDnPMHhZrDjLlN1DMjotlqt1pttrs7PtDvNTicziA0hkFAAFbg8Op4EDVeXC3AIPpZLAIDCkAAimACsBACEwWAwVAkMFwVCQ7BQuDqRpNmWg5stviwBVQ2DwVWg1nYfjgkoEGC9Fnl7CYHA6AC9ugwADLEABuxAQMGU1muUOUnlscLuykMFgR%2BsNxtN0C5fwxDi%2BLPUXyteFtpYduKum2sXkLkLcB3G8qAA

**Downlaodd file**
[WaterAllocations.csv](https://github.com/WSWCWaterDataExchange/WestDAAT/files/10551722/WaterAllocations.csv)

**Comment by rwjam** [comment]
Are we are talking about water rights in AZ that that have a 'Bushman' name to the owner?  The example given was for ID.

The attached WaterAllocations.csv is empty.

**Comment by rwjam** [comment]
This same error does not appear on the UAT.  If I had to guess, it something to do with uploading the data from UAT -> to PROD, and updating the Maptiler of the PROD too.

**Comment by rwjam** [comment]
For the water rights that should be in AZ under the bushman name, it's possible that our scripts may have removed that info.  They break their QANTITIY value out in different value, it's possible it was removed.

![image](https://user-images.githubusercontent.com/17555073/217386794-231745f0-e135-4ad6-b70b-c12e1e3a3c96.png)

**Comment by amabdallah** [comment]
Here is what shows up in WestDAAT now. I think this looks good to me. 

@rwjam Is the screenshot table from Excel(?) related at Bushman owner name or was this just an example of the different units AZ provides?
https://westdaatstaging.westernstateswater.org/?state=N4Ig7gTiBcoIYBsEHsDGcAuBLZA7A8mLgKZTQgBGArgM4AWAtnLiADQg0abE0wDaIAIIAtEAF12AB2QIAngiwl%2BEkLgQATLADEsCDKQAimODFAJMWDFXXEYuKknYpcAc0vXb0e45CaIxVGw8XmgAZnZ1YwAFZEUMEIB2AF8k9iZJUxAAL2RkBgAZYgA3YgQYAFYAOgAGABYAJlD6hIBGeuqANnqATnLepwsrGxgmyo7Q0NqW7uqADm7e0LanPDchzwBaFuqEypbQ8oba7oSO8tDuyZSgA



![image](https://user-images.githubusercontent.com/3268971/227043234-44df4a78-f920-47b3-a248-188bff3ab88d.png)
