### ISSUE TITLE
Data Table: Include Owner name

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/WestDAAT#201]
**Problem**
Summary table showing Owner classification 

**Solution**
Show owner name

------

**Context**

In this use case, I'm looking for who are the owners of big water rights in this area in California. The owner classification in this case is in-review which is not adding value. We probably should keep the classification, but need to add owner's name. This case is useful for a farmer-level water rights search which would be in-review or any other granular class TBD later. 

https://westdaat.westernstateswater.org/?state=N4Ig7gTiBcoEYFMB2CBmBLAxughgGwFUBnBImAbXmTS10JIDkcBbBGEAQQHMIsBXPABc%2BEBAAIAkhF5ccg9AHskIADQhMSon2YAHeUoDCchFwUQAnjACMAXxVUUGbPmIImrdgBEFrIvMyq6praeopIRoImZpbQtvYgiI60LowsbNAgADLoAG6kggqYANaBGkhauvrhxqYW1nYONM70bmnsALLoSF1cpcGVYRFRdbENCdROdK7u6SAACnxweFhiAMp8Ojp4lmplFaGGNdH18YlNU6keGQTlOgjYGAgAJn3lIVVDtTG2ALpqfsYyNByCADBwQH8QMwugA1BR4bTpKwABlRqLUOnh5mWKAooHQT2Q8keUAyyMwAHYAMyoCkANnJACZGRSnlTMJgqQAWQnIhBUp6oJ4AVn5mCeAE5Ak85DgYPiXmTKTT6UyWWyOdzefzBSKxZLAoJzHd2AAxBByERsDEQBR3CDyUjyuwgLgIHwIQQjUAaMxPLqAijkcgAWisVjpADphciqeGuVzGcKqSmrCoqVG6cK6VSKRLkQAOYWM2NUgt-UNWRlWSMlqnCiV08MSrkSllc9PCyNNukF6sU5OogsFqwVsNWAvRiO55nIiUUgvIxl09M1lsZ5F5gtcnMT3tj8NUyMj4UF-PCqzZkun1fR5nMhNxgtUzcZg9V7vIuklikU5e9xk43TI9CysKlGS5TcAKTZd3yjGM4ysBMkxTICM27bNc3zIs6zLH58LUI0TQyOYsVMZQbEoyEkDwf1TXQIQEAgTxZXlEA8DkdBhEJGAkAEPA1DwJQuC4vgeOgPi8AEkB-VETAqiBKk1BlQQcFIrpBCBClKLUZgcB0NiAC8FB8TIEDyPAYCjKwJRjWykObXskMEzjuPScDIz-BcUQvOMKWRC9BOE0TxPHLsJUvOkB0g5c%2BwTF1IEVUBMQ01Z0EM2YckCPSdAAcVtDYenYOA%2BBASigA

![image](https://user-images.githubusercontent.com/3268971/216123782-2256e263-867b-4f99-ba1e-cf1f809f96af.png)

**Comment by Rhipeus** [comment]
Some of the owner names are long and will probably need to be truncated and ellipsed.
