### ISSUE TITLE
Make NLDI drag and drop pin more intuitive. Change NLDI icon color or shape?

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/WestDAAT#222]
**Problem**
We are concerned that the drag and drop pin feature for the NLDI Filter tool isn't intuitive enough for our average user, and we would like to make it more evident to a new user that it is a tool and how it is used.

**Suggested solution** 
Ryan suggested maybe using this example (see image) as something with some 3D-like features, so it stands out more to the average user.

We would also like to change the text too.... 
- "_Drag and Drop the '**Pin Icon**' to the map to select your search location_"

![image (8)](https://user-images.githubusercontent.com/3268971/226000103-df7656ce-43ed-4941-92b2-1abc60326d32.png)

**Is this where the code lives?**
https://github.com/WSWCWaterDataExchange/WestDAAT/blob/develop/src/DashboardUI/src/components/NldiTab.tsx#L253

![image](https://user-images.githubusercontent.com/3268971/225756054-b154175c-ab7c-4973-80d7-0dad48ddc953.png)

**Comment by amabdallah** [comment]
Ryan suggested this icon and also suggested this text change 
Drag and Drop the 'Pin Icon' to the map to select your search location

![image (8)](https://user-images.githubusercontent.com/3268971/226000103-df7656ce-43ed-4941-92b2-1abc60326d32.png)

**Comment by yxlee61** [comment]
If we were to make the icon 3D, we can only change the icon on display here (and not the one on the map). It's easiest to just change the color here, and might be nicer if the icons match with the map?
![image](https://user-images.githubusercontent.com/6611953/226952573-1988527a-e169-4963-abb6-23a737fe83db.png)

if you still prefer to have a 3D icon for display, can you provide an .svg file for the icon? and confirming we're also changing the color of the pin on the map as well? feel free to pick another shade of red if desired, just need the hex code (example above is #FF0000)
