### ISSUE TITLE
Minor change to water right landing page

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/WestDAAT#224]
1. Let's make the "State Native Right Webpage" line a hyperlink instead using the provided WaterAllocationNativeURL value the states gives us. In some cases that native WaterAllocationNativeURL can somtimes be very long and could mess up the card orientation.
2. Let's also move this "State Native Right Webpage" line to the top of the card right after the "Native ID" field so its quickly visible and the first thing the user sees.
3. Let's rename both the Water Right and Site landing pages title into
"WaDE Water Right Landing Page"
"WaDE Site Landing Page"

![image](https://user-images.githubusercontent.com/3268971/225982854-8ad035d0-1b31-4f83-b6e0-59065d1b079a.png)

![image](https://user-images.githubusercontent.com/3268971/225983313-e40da628-b38b-4f38-8020-a3b300948a47.png)

**Comment by amabdallah** [comment]
@yxlee61 question, when no URL is available, is it the case that the webpage label doesn't show up at all? that's probably okay for now but wanted to understand the behavior since QA does not have a lot of data to let me test much
 
https://westdaatqa.westernstateswater.org/details/right/ORwr_WR74029?state=N4IgtgziBcIQhgFwKYBtUEsUFoBuBOEAGnHgAcZQAvAexrABllc0YBGABhNSSwFcAJshgAWAKwA6AMwAmDiIAcnfG3wip%2BGdxoA7AOb8hMbGxkyJ%2BAGwczMsQoUiA7PjFiAvu6A

![image](https://user-images.githubusercontent.com/3268971/227020327-0610f96b-b906-4a77-99de-b1a0995c05f1.png)

**Comment by yxlee61** [comment]
Yes, that was how I ended up implementing it. Is there a preferred way you would like this to be displayed? maybe back to "State Water Right Webpage: Unknown"?

**Comment by amabdallah** [comment]
I think "State Water Right Webpage: "Unavailable" is probably the best. That way we hint to that state that they need to make it available like other states. If we hide it, no one knows that we support it. Farming with no shaming lol
