### ISSUE TITLE
NLDI WaDE toggle is not working

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/WestDAAT#247]
@yxlee61 
In both QA and Staging, and even Prod, this Scope of Query in the NLDI section does not work for WaDE toggle button. Turn it off, the WaDE points still show up.

FYI this functionality was working before so mot sure what happened.

**Context**
This is a complex piece of functionality. NLDI uses the long. and lat. Coordinate as input to query the WaDE, USGS, and EPA sites that are indexed on the stream network upstream and downstream of that selected point on the map. WestDAAT then matches the SiteUUDs from that NLDI-returned JSON against what WaDE has. The match allows WestDAAT filters to work on WaDE NLDI sites.

https://westdaatstaging.westernstateswater.org/?state=N4Ig7gTiBcoA4HsA2BPJBLAdgUxgbQF0AaETJAE3QDF0kAXbCAEQEM6WZQk306BXcrmgBmABwA6AGzCATJJJIEmAOa8BQgLQBGAAwAWKaJ0BWEpQjYAxnXRKAzjGFm2LAAoIsdB9B0BfXyQAtixwnCAAXggIgQAy2ABu2EgwAJziOsI6AOzCejKiKXrGYloKPPyCjhKi%2BTIyOpJ6YpJZMlkKSqoVmroGLcZZenpGWfpaksYBpBToAILW6IkwdBB82CRklGHcNt1VUrLyIIoqapXQ2vqGJmboFgv2js7s7p7efr5AA

![image](https://user-images.githubusercontent.com/3268971/227282053-e811ced0-af7b-4fe4-97d7-16a7ca2428f7.png)

**Comment by yxlee61** [comment]
The filter is filtering on "westdaat_pointdatasource". I think we "lost" that property when merging the NLDI data points to the existing WADE points.

Original Wade site point from NLDI api query:
![image](https://user-images.githubusercontent.com/6611953/227579608-9bcb50bb-7a50-4508-8625-d365effcf0e2.png)

Actual Wade point metadata (missing "westdaat_pointdatasource"):
![image](https://user-images.githubusercontent.com/6611953/227582006-f1b9a943-4c07-478a-b70f-772657a9b2c5.png)

EPA site point example:
![image](https://user-images.githubusercontent.com/6611953/227579447-339babfa-6b74-480d-80c4-e33b7fc37994.png)

**Comment by amabdallah** [comment]
@yxlee61 so do we need to add this property "westdaat_pointdatasource" to the Mapbox tiles to fix this issue?

**Comment by yxlee61** [comment]
@amabdallah can you add that on maptiler? it would be "westdaat_pointdatasource": "Wade"

**Comment by amabdallah** [comment]
@yxlee61 here it is 
https://github.com/WSWCWaterDataExchange/WestDAAT/blob/develop/src/API/WesternStatesWater.WestDaat.Tools.MapboxTilesetCreate/Program.cs

**Comment by amabdallah** [comment]
https://github.com/WSWCWaterDataExchange/WestDAAT#update-mapbox-vector-tileset
