### ISSUE TITLE
Remove "Consumptive" as a ben. use(?) value

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/WestDAAT#274]
https://westdaat.westernstateswater.org/?state=N4Ig7gTiBcoA4HsA2BPJBLAdgUxgbQF0AaETJAE3QDF0kAXbCAEQEM6WZQk306BXcrmiY%2BSJCSQJMAc14ChIsSUoRsAYzropAZxgBmZWxYAFBFjq7oAdgC%2BJAEbYcAM3Rr0LJAFVt2S3lBHFzcPb18AORYAWyEQAGEdPii4TQA3XBI1ROTNKTi2bGkECBQYAEYbAjsQKJY4ThAALwQEKIAZbHSkGAAWCR5%2BQV6ABgA6YYnJqYmATjKJKVlBoQBaMonx6emymb0bGyA

![image](https://user-images.githubusercontent.com/3268971/234265236-3f98b352-b43c-4040-b4da-d8dad36bc3d3.png)

**Comment by rwjam** [comment]
Resolved.
