### ISSUE TITLE
Add map theme selection to the landing pages

### ISSUE THREAD

**Issue by Rhipeus** [WSWCWaterDataExchange/WestDAAT#279]
The landing pages currently only allow the satellite theme for displaying the sites.  Sometimes however, it would be better to use other themes, like the basic light map used on the home page by default, so that things like town and river names can also be seen on the map.  Adding the option to change the map theme gives users this ability.

**Comment by amabdallah** [comment]
This is how it would look like 

![image](https://github.com/WSWCWaterDataExchange/WaDE2.0/assets/3268971/154d7c5b-f333-4b5d-a561-e78b29f476b0)
