### ISSUE TITLE
Allow users to download the entire water rights database through a scheduled mass-download file

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/WestDAAT#292]
Similar to the JSON-LD file that is generated overnight or once a week, we need a utility that prepares a mass-data download to be accessed by users needing more than 100 K records. 
https://github.com/WSWCWaterDataExchange/WestDAAT/tree/develop/src/API/WesternStatesWater.WestDaat.tools.JSONLDGenerator

Since this data is generated once and stored in blob storage, we can allow users with an account to download it. We need to track each user's data download and the 100 K download.

**Comment by amabdallah** [comment]
Example JSON-LD mass download
https://westdaat.westernstateswater.org/jsonld.json 

We need to add the user token as part of this URL. So we track who is downloading the Json-ld

**Comment by rwjam** [comment]
For water right data only, files created and saved on google drive for public download: https://drive.google.com/drive/folders/1jyKLqVvbK2Hwk89tfs44DL5rIGp5bRG3

**Comment by rwjam** [comment]
A comment and concern with this approach, if we allow a mass download option like this, are we able to track who is downloading and using the data?  Are we concerned with some individuals taking that public data and selling it off as if they had gathered it themselves?

**Comment by amabdallah** [comment]
@rwjam That's a great point. How about we close this Google Drive link to only folks we "collaborate" with, per their request? Meaning that we need their email to share it with them. I can add a sentence asking interested users to email us.
