### ISSUE TITLE
Remove "Not applicable" from Beneficial Use values

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/WestDAAT#313]
https://westdaat.westernstateswater.org/?state=N4IgtghgDiBcoC8D2SwBkCmA3DAbOAzAHQCsAbAQQEwCMFdALAQAw0CcANCLhAC4CWvAK4ATDHAbMiAdjo0CXXEgB2Ac0GjxsALQAONkWaTp0gL5cA7gCc4oAEYZlGAGb8Axvwi4AqgGcMAHIQYBi%2BcADaIAFIvAAEAIJQULjuEHa44gC6XPy%2BAbgi-ABi-Li8GFbxbgI4cM5e-qamQA

![image](https://github.com/WSWCWaterDataExchange/WestDAAT/assets/3268971/1dca3876-c487-4c75-9ae3-930500003fce)

**Comment by rwjam** [comment]
Issue resolved. Just a "_Not Applicable"_ wade beneficia use label squeezed in for an unspecified use.
