### ISSUE TITLE
Update this documentation page: How to Use WestDAAT Filters?

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/WestDAAT#341]
Let's update the screenshots to reflect the minor changes made to the filters since those were taken a year ago.
https://westernstateswater.org/wade/westdaat-filter-documentation/

We probably should add the link to the hamburger menu
![image](https://github.com/WSWCWaterDataExchange/WestDAAT/assets/3268971/47a9b1c0-7a5d-4abd-9ac0-c3a0bca08963)

**Comment by rwjam** [comment]
imagery updated https://westernstateswater.org/wade/westdaat-filter-documentation/
