### ISSUE TITLE
Tons of unknown beneficial uses

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/WestDAAT#6]
@rwjam, when you have some time, would you look into what does this "unknown". Colorado and Arizona seem to have a tone of them. It could be related to the "null" issue or to how Tseganeh (if any) map things back then. 

In the CVs, we have both "Unknown" and "Unspecified" values. I think a water right in general by definition must have a beneficial use. So if the field is missing in any state's data, we probably should drop and delete the "Unknown" and keep "Unspecified". 

http://vocabulary.westernstateswater.org/beneficialusecategory/

https://wade-mapbox-prototype.azureedge.net/
![image](https://user-images.githubusercontent.com/3268971/107293061-2d872600-6a28-11eb-8310-4dc8f3f3aade.png)

**Comment by rwjam** [comment]
"Unknown" as been changed to "Unspecified" for consistency.

Started making a few improvements in the existing QA data, which both solved and made more Unspecified spots.  Some of that is just the existing data from the states.  

Will need to spend some time with each reviewing their data and making improvements.  Started with CO already.

![image](https://user-images.githubusercontent.com/17555073/107700184-5ef43180-6c74-11eb-9df4-ef2ac5d5d8cb.png)

**Comment by amabdallah** [comment]
Very cool! thank you for working on that. Looking at the states' terms, I'm wondering now if "Unspecified" is a good one but it should be fine for now. This is a great finding and we definitely need to ask DPL to add a counter for PODs and Water Rights within the portal. e.g., show how many unspecified water rights out there. A more advanced plot would be to show a dynamic bar chart count for the ~20 beneficial uses
