### ISSUE TITLE
WestDAAT Errors 03/31/2022

### ISSUE THREAD

**Issue by rwjam** [WSWCWaterDataExchange/WestDAAT#64]
Below are a few errors we caught when doing a demo of WestDAAT on March 31, 2022.

1. Seems like the **Rest Filter Button** is working as intended for the map, but not the filters themselves.  Ideally when pressed the **Rest Filter Button** would also reset all the filters back to a default / launch app state.
![Reset Filter Button isn't resetting filters](https://user-images.githubusercontent.com/17555073/161293230-91e8d9cb-4aca-4cc9-860a-3add82dabeca.png)

2.  There is a transparency issue with POU polygons around the Las Vegas area.  We suspect the error is caused due to too many polygons layered on on top of one another at this location.  We will verify if this is this case and determine how we can solve this issue on our end.  We are also open to suggestions if we cannot solve this issue ourselves / if this is the true state of the data and cannot be changed.
![Transparency of POU vs POD in LV](https://user-images.githubusercontent.com/17555073/161293436-68893843-c981-4ee8-a990-e6a0d0e730f9.png)

3. There is a discrepancy between the **Priority Date** posted on the popup card and the **Priority Date Filter** inputs for the UT data.
![UT priority date issue](https://user-images.githubusercontent.com/17555073/161293958-1b8b1a6a-afde-4ba7-b8fc-0c5205969557.png)

4.  When displaying sites by Water Source Type some sites in OR appeared as block dots.  We suspect this was due to updates we had pushed to the QA, but the vector tiles themselves had not been updated to reflect those QA changes.  As a whole, we suspect this will not be an issue in the long run as this should be resolved anytime the vector tiles are updated.  We will either need assistance updating those vector tiles every time we push changes to the QA, or instruction on how we can update the vector tiles ourselves.
![What are these black dots and missinglanding plages](https://user-images.githubusercontent.com/17555073/161295914-9e786865-a9a2-4b9a-b392-ad14556c88d9.png)

**Comment by amabdallah** [comment]
These bugs seem to be fixed, as I'm finding on WestDAAT. All good.
