### ISSUE TITLE
Check if we have more Hydro and Thermo electric + Snow beneficial uses in QA db?

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/WestDAAT#74]
I was expecting to see more Hydro and Thermo electric + snow water rights than shows up here 
![image](https://user-images.githubusercontent.com/3268971/161999981-ffaef8f7-1f38-4518-8aac-611369494894.png)

![image](https://user-images.githubusercontent.com/3268971/162000182-3d389474-dbcd-4b4d-a1e4-93e451a0f443.png)

![image](https://user-images.githubusercontent.com/3268971/162000846-e59eefef-23ef-45c7-b27a-ddfe0e3d3d1c.png)

**Comment by amabdallah** [comment]
Is this a screenshot from WestDAAT? No matter how much I zoom in, I'm not seeing much as this screenshot

**Comment by rwjam** [comment]
This is a screen shot of Tableau using a query I did to get all WaDE recognized Hydroelectricsites & Thermoelectric Cooling water right sites.

**Comment by amabdallah** [comment]
Thank you. All is working fine now. We'd need to look into clustering sites when there are so few across the West. For now, the Analytics and Table section help with that.

**Thermoelectric** 
https://westdaat.westernstateswater.org/?state=N4Ig7gTiBcoEYFMB2CBmBLAxughgGwFUBnBImAbXmTS10JIDkcBbBGEAFQAsEJmB7BHgSYALhCwACAML9%2BedEgDmIADQhM-JEQCuzAA6j0W6TlEIl-CAE8YABgC%2BAXXX751hSgouQSPABN0ADF0PHMIABEzHBhQPDN0UR1-NmgkHTw8dTwtJUTk1PTM9UCIESMtMmgAZhLogAV%2BRVEqgHYHB3VmHH1YkAAvOWYAGQQANyEYAFYAOjsAJgAWVoA2AA4ATiXWtfmARj2V7ISklJhFuzn1nfnWi8WHuyns3Pyz6ABaPbsNmdapp5TFYXebzOxrVrtBxAA

**Hydroelectric** 
https://westdaat.westernstateswater.org/?state=N4Ig7gTiBcoEYFMB2CBmBLAxughgGwFUBnBImAbXmTS10JIDkcBbBGEACQE8ATCAewR4EmAC4QsIADQhM-JEQCuzAA6j08gMI5RCAOb8IXGACYAvgF0ZK-ni550KClZBI8PdADF0eXRAAiOjgwoHg66KKKPGzQSIp4eDJ48noRUTFxCTIeECLq8mTQAMzZQQAK-I6ihQDsZmYyzDgqISAAXvz8zAAyCABuQjAArAB0AAwmACw1AGwAHACcUzVzJgCMazNJ4ZHRMJNj4-MrJjUHkxdrRUNJKWl70AC0a2MLIzVDY0NDMwcmJmM5rN6kA
