### ISSUE TITLE
Update the points count to be queried from the database not from the tiles

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/WestDAAT#76]
We need to update the count to be the real total number, not just the points on the top tile. 
Should we have two counts, one for POU and another for POD sites? Example

- 38353 Points of Diversions Displayed
- 22217 Points of Places of Use Displayed

![image](https://user-images.githubusercontent.com/3268971/162059019-6c90c9ea-9cee-4bcd-86e3-2a7679f367c1.png)

**Comment by rwjam** [comment]
Update as of 06/08/2022.

- 1,437,010 water records in Core. AllocationAmounts_fact table.
- 2,763,639 wr sites in the Core.Sites_dim table.
- 2,333,597 sites tired to a wr through the Core. AllocationBridge_Sites_fact table.

 -----------------------------
As a heads up, there are (2,763,639 - 2,333,597) = **430,042** orphan wr sites in the Core.Sites_dim table that are not tied to any water right record.   Our data processes involves identifying site, then identifying water records with its related sites.  The WaDE2 data uploader works similarly of uploading sites, then uploading water records with its related sites.  But there is that disconnect there that a site we identified / uploaded may not in fact be tied to any of the water rights uploaded.

I believe we can solve this easily on the data processing end before it goes into WaDE if we start to do a few more data / validation checks to prevent orphan sites such as these from going into the database in the first place.

**Comment by amabdallah** [comment]
As a quick solution due to a limited budget, we removed this account for now. Users can look at the correct count as part of the piechart analytics
