### ISSUE TITLE
water right landing page: variable info + controlled vocabulary 

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/WestDAAT#79]
1. For the variable metadata, let's not show this item because it can be confusing (the unit is already included in the field name):
**Maximum Amount Unit**: CFS
2. We also need to show and distinguish the WaDE controlled terms next to the native terms. e.g., AllocationLegalStatusCV with a hyperlink that takes the user to the CVs webpage that contains all the CVs of that term. Note, the meeting we decided to have one hyperlink next to beneficial uses filter to this webpage http://vocabulary.westernstateswater.org/beneficialusecategory/
We probably want to the the same to all other controlled vocabulary (CV) filters

3. We want to add most of the metadata items listed here such as CropTypeCV,CustomerTypeCV, CommunityWaterSupplySystem, AllocationCropDutyAmount, WaterAllcationNativeURL, ExemptOfVolumeFlowPriority, DataPublicationDate. See here
https://schema.westernstateswater.org/tables/Core_AllocationAmounts_fact.html

https://westdaatqa.azureedge.net/details/right/2802286
![image](https://user-images.githubusercontent.com/3268971/163020730-9ce55d74-7bde-4507-9b1b-66b577423580.png)

**Comment by rwjam** [comment]
Made that change to 'Allocation'.
